OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/14)

add r2d4 to approvers

---

fairing/training/native/decorators.py
fairing/training/native/deployment.py

usage: `@native.Training(output=True)`
Fixes #45
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/58)

deploy: optionally print out manifests

---

OWNERS

I am part of the Cloud AI platform team at Google and will be actively working on Fairing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/60)

Adding myself to the reviewers list

---

fairing/backend/kubernetes/manager.py
fairing/training/kubeflow/deployment.py

/assign @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/61)

update tfjob to v1beta1

---

fairing/backend/kubernetes/__init__.py
fairing/backend/kubernetes/manager.py
fairing/builders/append/append.py
fairing/training/kubeflow/deployment.py
fairing/training/native/deployment.py

I'm using vscode with the autopep8 formatter which caused most of the diff.  I added comments under each actual change below.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/62)

Refactored tfjob version, optional output, added resource_limits 

---

OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/70)

Add rpasricha to Fairing reviewers

---

OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/72)

Updating approvers list

---

Dockerfile
fairing/builders/append/append.py
fairing/builders/base_builder.py
fairing/builders/cluster/cluster.py
fairing/builders/cluster/gcs_context.py
fairing/builders/docker/docker.py
fairing/kubernetes/manager.py

Add an option to skip pushing the docker image for testing or local clusters like minikube or docker for desktop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/67)

Add push switch to builders

---

examples/simple/main.py
fairing/builders/append/append.py
fairing/config.py
fairing/deployers/job/job.py
fairing/functions/function_shim.py
fairing/preprocessors/base.py
fairing/preprocessors/function.py
fairing/runtime_config.py

Needs #67 first
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/68)

Add a basic function preprocessor

---

examples/notebook/hello-world.ipynb
examples/simple/main.py
fairing/config.py
fairing/functions/function_shim.py
fairing/notebook/notebook_util.py
fairing/preprocessors/function.py
requirements.txt
tests/preprocessors/test_function_preprocessor.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/85)

Modified function preprocessor to use cloudpickle

---

.dockerignore
Dockerfile.test
cloudbuild.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/92)

Add cloud build Dockerfile and build steps

---

examples/distributed-training/main.py
fairing/builders/append/append.py
fairing/builders/base_builder.py
fairing/builders/cluster/cluster.py
fairing/builders/docker/docker.py
fairing/config.py
fairing/deployers/job/job.py
fairing/deployers/tfjob/tfjob.py

Some fixes and improvement while I was testing the library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/97)

some fixes and improvements

---

OWNERS

/assign @rpasricha
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/105)

Removing reviewers who are not active

---

fairing/config.py

It should be a no-op
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/114)

remove set_model/get_model from config

---

examples/distributed-training/main.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/115)

update distributed training example

---

README.md

I updated the ReadMe.md file with the following:
- Reviewed text for grammar and clarity
- Reviewed for usage of the Kubeflow Fairing name
- Revised the doc to try to help explain anything that I felt might be unclear.
- Revised the doc for structure, e.g. renaming the "Overview" section as "Features" and moving up towards the top.
Please let me know if you have any suggestions or requests. Also, please review the content I added for technical accuracy.
Once we are happy with this doc, please hold off on merging the PR so I can ask another writer to review the PR as well.
Thanks,
Joe
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/116)

Update to ReadMe.md

---

fairing/builders/docker/docker.py
fairing/builders/dockerfile.py
tests/unit/builders/test_dockerfile.py

Fixes #131
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/132)

Setting docker command in docker builder

---

fairing/builders/base_builder.py
fairing/cloud/gcp.py
fairing/deployers/job/job.py
fairing/deployers/tfjob/tfjob.py
fairing/kubernetes/manager.py
tests/integration/test_kubeflow_training.py

Fixes #106 
Move credential mounting to Kubernetes manager and update both Job and TFJob deployers to mount credentials if desired.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/136)

Refactor Service Account Credentials

---

README.md

Fixes #127 
The real requirements are only a kubeconfig + docker config.json but new users probably won't have those without downloading the kubectl and docker CLI tools. 
Also added a sentence about using it directly on Kubeflow notebooks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/138)

add more context

---

fairing/builders/cluster/cluster.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/137)

add pod spec mutators for cluster builder

---

requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/140)

Jupyter requires tornando lower than 6

---

fairing/preprocessors/base.py
fairing/preprocessors/full_notebook.py

* Normalize filepaths in base preprocessor (to avoid further duplicates)
* Add `input_files` argument to full_notebook preprocessor
* Updates to jupyter nbconvert command
* Allow execution to continue if one cell fails with an error
* Remove timeouts on cell execution
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/142)

Full notebook preprocessor updates

---

examples/kubeflow-gke/main.py
examples/kubeflow/main.py
examples/kubernetes-in-cluster-builder/main.py
examples/kubernetes/main.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/147)

lint the examples a bit

---

Dockerfile.test
cloudbuild.yaml
setup.py

Fixes #150 
The \_\_init\_\_.py files in tests dir is needed for the code coverage to work!
Coverage report for this PR.
```
Step #2: ----------- coverage: platform linux, python 3.5.7-final-0 -----------
Step #2: Name                                          Stmts   Miss  Cover
Step #2: -----------------------------------------------------------------
Step #2: fairing/__init__.py                               6      1    83%
Step #2: fairing/builders/__init__.py                      0      0   100%
Step #2: fairing/builders/append/__init__.py               0      0   100%
Step #2: fairing/builders/append/append.py                54      0   100%
Step #2: fairing/builders/base_builder.py                 26      2    92%
Step #2: fairing/builders/builder.py                       8      2 …
```

 Adding code coverage for pytest tests

---

fairing/builders/cluster/cluster.py
fairing/builders/cluster/gcs_context.py
fairing/builders/docker/docker.py
fairing/builders/dockerfile.py
fairing/preprocessors/base.py
tests/integration/common/test_kubeflow_training.py
tests/unit/builders/test_dockerfile.py
tests/unit/preprocessors/test_base_preprocessor.py

Fixes #154 #152
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/158)

Installing requirements earlier and fixing issues with cluster builder

---

fairing/builders/cluster/gcs_context.py

We do this in the pod_spec_mutator functions now
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/159)

Skip creating secret in context preparer

---

examples/prediction/xgboost-high-level-apis.ipynb
examples/prediction/xgboost-train-and-deploy-in-gcp-from-local-notebook.ipynb
fairing/deployers/serving/serving.py
fairing/kubernetes/manager.py
fairing/ml_tasks/tasks.py

Fixes https://github.com/kubeflow/fairing/issues/149
Fixes https://github.com/kubeflow/fairing/issues/124
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/157)

Add prediction client

---

fairing/cloud/gcp.py

fixes #164
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/165)

create bucket if it doesnt exist

---

examples/prediction/xgboost-high-level-apis.ipynb
examples/prediction/xgboost-train-and-deploy-in-gcp-from-local-notebook.ipynb
fairing/cloud/gcp.py
fairing/deployers/serving/serving.py
fairing/kubernetes/manager.py
fairing/ml_tasks/tasks.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/168)

v0.5 cherrypicks

---

fairing/backends/backends.py

Fixes #174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/175)

Default Kubeflow backends to Job

---

fairing/deployers/serving/serving.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/177)

call get_service_external_endpoint correctly

---

OWNERS

././
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/182)

Adding myself to approvers

---

examples/prediction/xgboost-high-level-apis.ipynb
examples/prediction/xgboost-train-and-deploy-in-gcp-from-local-notebook.ipynb
fairing/ml_tasks/tasks.py

fixes #179
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/181)

Fix prediction

---

requirements.txt

fixes #185
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/186)

updated requirements for Kubernetes client lib

---

setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/188)

Bumping version to 0.5

---

examples/prediction/xgboost-high-level-apis.ipynb

Hello,
I've added some text to the xgboost-high-level-apis notebook to help users that are working through the Local Notebook instructions. Please let me know if there are any changes that you would recommend.
Thanks,
Joe
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/190)

Adds process descriptions to xgboost-high-level-apis.ipynb.

---

setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/192)

add build version

---

setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/193)

cut v0.5.2

---

fairing/deployers/job/job.py

Fixes #198
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/205)

Add labels to deployment

---

OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/210)

Remove rpasricha from owners file

---

examples/prediction/xgboost-high-level-apis.ipynb

cc @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/214)

update documentation on xgboost example notebook

---

fairing/backends/backends.py
fairing/builders/append/append.py
fairing/builders/base_builder.py
fairing/builders/cluster/cluster.py
fairing/builders/docker/docker.py
fairing/config.py
fairing/deployers/serving/serving.py
fairing/ml_tasks/tasks.py
fairing/preprocessors/base.py

* For AppendBuilder set working directory to /app so that files are on
the python path
* Set default to ClusterIP for the service.
Related to #206
There's some ongoing discussion about the right long term solution but
I think its better to lock things down in the short term.
* Add more logging.
* Print out the full in cluster URL of the service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/207)

Add logging, set working directory and service type.

---

prow_config.yaml

this will make the presubmits pass until I add the actual configuration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/220)

placeholder prow config

---

fairing/deployers/gcp/gcpserving.py
tests/unit/deployers/gcp/test_gcpserving.py

Fixes #143
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/189)

Integrate GCP Serving deployer with deployer interface

---

README.md

Updates the readme.md file to refer users to the Fairing docs on Kubeflow.org.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/231)

Updates readme.md to refer users to the docs site

---

tests/unit/preprocessors/test_converted_notebook_preprocessor.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/226)

Added tests for converted notebook preprocessor

---

roadmap.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/245)

Plans for Q2

---

fairing/__init__.py
setup.py
tests/integration/gcp/test_user_agent.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/249)

Bumping the minor version for a release

---

examples/lightgbm/Dockerfile
examples/lightgbm/simple-training.ipynb
fairing/frameworks/lightgbm.py
tests/unit/frameworks/test_lightgbm.py

Summary:
1. Added native support for LightGBM, specially using its CLI version. Subtask of #242 
1. Added unit tests
Followup tasks:
1. Add distributed training for LightGBM #242 
1. Detailed documentation
1. Integration tests
1. Integrate with the backends API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/252)

Added native support for LightGBM 

---

fairing/config.py
fairing/deployers/gcp/gcp.py
fairing/deployers/job/job.py
fairing/ml_tasks/tasks.py

Fix #257
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/261)

return job name from deployer

---

examples/lightgbm/Dockerfile
examples/lightgbm/distributed-training.ipynb
fairing/frameworks/lightgbm.py
fairing/frameworks/utils.py
fairing/kubernetes/utils.py
tests/unit/kubernetes/test_utils.py

Summary:
1. Added resource specification (CPU, and Memory) for pods in LightGBM API
1. Added ability to specify pod spec mutators to serve as an escape hatch for the functionalities not exposed by the API
1. Increased nslookup retires to adapt to delays in node provisioning in auto scaled node pools
1. Added unit tests
1. Added crcmod to Dockerfile to improve download speed in gsutil
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/262)

Added resource specification for pods in LightGBM API

---

fairing/deployers/job/job.py

Fix #268
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/269)

add backofflimit to avoid job recreation

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/270)

Added issue/pr template.

---

examples/pytorch/mnist/mnist.ipynb
examples/pytorch/mnist/requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/241)

PyTorch notebook examples

---

examples/train_job_api/main.ipynb
examples/train_job_api/train.ipynb
fairing/backends/backends.py
fairing/cloud/gcp.py
fairing/deployers/job/job.py
fairing/ml_tasks/tasks.py
fairing/ml_tasks/utils.py
fairing/preprocessors/base.py
fairing/preprocessors/function.py
tests/unit/preprocessors/test_notebook.py

1. Currently TrainJob API only supports Python function/class. This PR adds support for executing python files and full notebook execution.
2. Exposes pod_spec_mutator argument in TrainJob API that lets user to customize pod spec like CPUs and mount volumes
3. Improved how we pick the builder in TrainJob API. Now it uses AppendBuilder when no python package installation is required. Also makes sure right gcp secret is available before executing cluster builder.
4. Improved error messages
5. Added an example notebook - examples/train_job_api/main.ipynb
Fixes #203 #166 
**Special notes for your …

Adding different entry point options to Train Job API

---

fairing/ml_tasks/tasks.py
fairing/ml_tasks/utils.py

Fixing a bug where set used instead of an array.
Fixes #
NA
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/280)

Minor bug fix in TrainJob API

---

fairing/functions/function_shim.py
fairing/preprocessors/function.py
tests/integration/common/test_py_version_checking.py

Check python version during execution for function preprocessor.
In the patch we just compare the Python major and minor version, and igore micro version, for examples, 3.6.5 will mismatch with 3.5.2, but match with 3.6.8. 
After the patch, if the major and minor version are same, then continue. Otherwise, will exit and print beflow error message from pod:
```
[root@jinchi1 simple]# kubectl logs fairing-job-55rzc-bz9fh -n default
Traceback (most recent call last):
File "test.py", line 24, in <module>
compare_version(args.python_version)
File "test.py", line 18, in compare_version
+ local_python_version + ' in the local environment.')
RuntimeError: The Python version 3.6 mismatches with Python 3.5 in the local environment.
```
**Which issue(s) this …

Check python version for function preprocessor

---

examples/prediction/xgboost-gkeop.ipynb

This is forked from xgboost-high-level-apis.ipynb, and changed the part that do remote training and deployment.
/cc @karthikv2k 
/cc @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/301)

Add xgboost example for gke on prem

---

OWNERS

Add me to OWNERS, as I'm very interested in faring, and tested some cases for on-prem cluster, and fix some bugs, contributing features such as supporting kfserving and pylint checking (almost done). Will continue contributing and maintaining the project from IBM side. Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/303)

add jinchihe to owners

---

fairing/constants/constants.py
fairing/deployers/job/job.py
fairing/deployers/serving/serving.py

The PR is to do:
1. Fixed the problem in the #312
Before fixing when deployer tfjob and job, always show "Training job ..." as below:
```
Training job fairing-tfjob-svdtv launched.  
```
After the fixing, the message will be as following for tfjob deployer:
```
The tfjob fairing-tfjob-fgtxq launched.
```
and for job deployer:
```
The job fairing-job-s4q2d launched.
```
2. clear constants in the `job.py` and `serving.py`, to be constants, we should define the constants in the `constants.py`
Fixes #312 
1. Please confirm that if this PR changes any image …

fix one message issue and classify constants

---

fairing/deployers/serving/serving.py

support pod_spec_mutators in Serving deployer so that user can add secret volumes to the serving deployer.
Fixes #256 
```release-note
support pod_spec_mutators in Serving deployer
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/327)

support pod_spec_mutators in Serving deployer

---

tests/e2e.sh

Fix the integration tests problem.
Fixes #336 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/337)

fix integration tests problem

---

fairing/preprocessors/function.py

Issues Fixed: #323 Redundant Code
assign @karthikv2k
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/339)

Changes for #323

---

OWNERS

Recently focus on fairing and provided lots of PR for Fairing, and delivered some key features, and for now working for Fairing documents and doing more for on-prem cluster with Fairing. 
Update owner for better maintain and contribution. Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/345)

update owner for jinchihe

---

fairing/functions/function_shim.py
fairing/http_utils.py
fairing/kubernetes/manager.py
fairing/kubernetes/utils.py
fairing/utils.py

Update docstrings under kubernetes and functions (@jinchihe owned parts).
Related with #326 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/346)

Update docstrings under kubernetes and functions

---

kubeflow/fairing/__init__.py
setup.py

Update kubeflow-fairing version to 0.6.0 and release to Pypi.
Fixes #370 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/378)

update kubeflow-fairing version to 0.6.0

---

kubeflow/fairing/backends/backends.py

Fixes #371 
```release-note
Add service_type in serving deployer for aws
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/372)

Add service_type in serving deployer for aws

---

kubeflow/fairing/functions/function_shim.py
kubeflow/fairing/preprocessors/function.py
tests/integration/common/test_py_version_checking.py

Fixes #340 
1. We only retrieve major and minor version for comparison in the code. 
2. Actually, this is not perfect because of potential incompatibility issue. Better to make sure remote running py version > notebook python version.  
```
Potentially compatible: Python version x.y is potentially compatible to version w.z if x == w and y < z
```
In order to strictly follow what python official doc suggest us, we need to retrieve full version and then. I can make this change if you think that's reasonable.
```
from packaging import version
if …
```

Fix python compatibility issue

---

kubeflow/fairing/config.py
kubeflow/fairing/deployers/deployer.py
kubeflow/fairing/deployers/gcp/gcp.py
kubeflow/fairing/deployers/gcp/gcpserving.py
kubeflow/fairing/deployers/job/job.py
kubeflow/fairing/deployers/kfserving/kfserving.py
kubeflow/fairing/deployers/serving/serving.py
kubeflow/fairing/deployers/tfjob/tfjob.py
kubeflow/fairing/frameworks/lightgbm.py
kubeflow/fairing/frameworks/utils.py

#326 
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/354)

generate docstring for config, deplyer, frameworks

---

kubeflow/fairing/backends/backends.py

add doc for backends code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/390)

add docstring for backends

---

kubeflow/fairing/preprocessors/base.py

To address the issue #326 , Thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/389)

Add the code comment

---

kubeflow/fairing/preprocessors/full_notebook.py

To address the issue #326 , Thanks
/cc @jinchihe ,Could you review this, Thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/391)

Add the comments

---

kubeflow/fairing/preprocessors/function.py

To address the issue #326 , Thanks
/cc @jinchihe ,Could you review this, Thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/392)

Add the comments for the python API functions.

---

kubeflow/fairing/preprocessors/converted_notebook.py
kubeflow/fairing/preprocessors/full_notebook.py

To address the issue #326 , Thanks
/cc @jinchihe ,Could you review this, Thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/393)

Doc fairing comment4

---

kubeflow/fairing/builders/cluster/azurestorage_context.py
kubeflow/fairing/builders/cluster/gcs_context.py
kubeflow/fairing/builders/cluster/s3_context.py
kubeflow/fairing/constants/constants.py

Move kaniko image constant to constants
Fixes #
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/398)

Move kaniko image to constants

---

kubeflow/fairing/cloud/aws.py

the docString for cloud aws
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/402)

docString for cloud aws

---

kubeflow/fairing/notebook/notebook_util.py

Add doc into python file in notebook for issue https://github.com/kubeflow/fairing/issues/326
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/401)

Add doc to notebook

---

kubeflow/fairing/builders/append/append.py
kubeflow/fairing/builders/base_builder.py
kubeflow/fairing/builders/builder.py
kubeflow/fairing/builders/cluster/azurestorage_context.py
kubeflow/fairing/builders/cluster/cluster.py
kubeflow/fairing/builders/cluster/context_source.py
kubeflow/fairing/builders/cluster/gcs_context.py
kubeflow/fairing/builders/cluster/s3_context.py
kubeflow/fairing/builders/docker/docker.py
kubeflow/fairing/builders/dockerfile.py

add comments to some methods, made code easy to read.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/396)

add member comments to some methods

---

kubeflow/fairing/ml_tasks/tasks.py
kubeflow/fairing/ml_tasks/utils.py
kubeflow/fairing/notebook/notebook_util.py

Comment python functions in ml_task . Issue https://github.com/kubeflow/fairing/issues/326
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/400)

Add doc into ml_task

---

kubeflow/fairing/builders/cluster/cluster.py
kubeflow/fairing/builders/docker/docker.py
kubeflow/fairing/builders/dockerfile.py
tests/integration/common/Dockerfile.test
tests/integration/common/test_kubeflow_training.py

Allow setting custom Dockerfile for ClusterBuilder by setting `dockerfile_path`, if the `dockerfile_path` is not set, will generate the Dockerfile
Fixes #404 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/405)

Allow setting custom Dockerfile for ClusterBuilder

---

examples/kfserving/main.py
kubeflow/fairing/constants/constants.py
kubeflow/fairing/deployers/kfserving/kfserving.py
kubeflow/fairing/kubernetes/manager.py
requirements.txt
tests/unit/deployers/kfserving.py

Enhance kfserving integration, move to new version of kfserving, and the CRD has been changed to Inferenceservice, updated in Fairing accordingly.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/407)

Enhance kfserving integration

---

kubeflow/fairing/deployers/tfjob/tfjob.py

Add annotations param to TfJob for ability to pass it to Job.
Fixes #
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/406)

Add annotations param to TfJob

---

README.md
kubeflow/fairing/__init__.py
setup.py

1. Release kubeflow-fairing 0.7
2. Add link for kubeflow-fairing API docs.
Fixes #411
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/412)

release kubeflow-fairing 0.7 and add doc links

---

kubeflow/fairing/backends/backends.py

fixed issue #315 
@jinchihe ,Could you review this, thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/420)

fix logical bug

---

kubeflow/fairing/constants/constants.py

Update kaniko image from version v0.7.0 to 0.14.0
Fixes #426
>> Updated kaniko image from version v0.7.0 to 0.14.0
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/427)
Quick test for the new URL:

Update kaniko image from version v0.7.0 to 0.14.0

---

examples/prediction/Dockerfile
examples/prediction/requirements.txt

xgboost-train-and-deploy-in-gcp-from-local-notebook.ipynb run failed, details see issue #283, Fix it.
UT PASS, remote_train() could run successfuly now:
```
mean_absolute_error=18173.15
Model export success: trained_ames_model.dat
ServiceException: 401 Anonymous caller does not have storage.objects.list access to fairing-demo.
Best RMSE on eval: %.2f with %d rounds 28787.720703 50
Model saved to gs://fairing-demo/housing_serve/trained_ames_model.dat
```
Fixes #283
1. Please confirm that if this PR changes any image versions, then that's the sole change this …

Fix remote_train issue in xgboost-train

---

kubeflow/fairing/kubernetes/manager.py
requirements.txt

Fix connect breaken problem while following logs after deploying, see more in #437 
Fixes #437 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/438)

Fix problem connect breaken

---

kubeflow/fairing/config.py
kubeflow/fairing/constants/constants.py
kubeflow/fairing/deployers/pytorchjob/pytorchjob.py
kubeflow/fairing/kubernetes/manager.py
requirements.txt
tests/integration/common/test_kubeflow_training.py

Support deploying pytorchjob using Kubeflow Fairing
Fixes #
```release-note
Support deploying pytorchjob using Kubeflow Fairing
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/436)

Support deploying pytorchjob using Kubeflow Fairing

---

examples/prediction/README.md

Fixes #441 
/cc @jinchihe , please review this, Thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/442)

Refresh the deploy service process.

---

setup.py

Release kubeflow-fairing 0.7.1
Fixes #440 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/446)

Release kubeflow-fairing 0.7.1

---

kubeflow/fairing/backends/backends.py
kubeflow/fairing/builders/cluster/cos_context.py
kubeflow/fairing/cloud/ibm_cloud.py
kubeflow/fairing/constants/constants.py
requirements.txt
tests/unit/cloud/test_ibm_cloud.py

Support ibm cloud 
Fixes #469 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/479)

Support IBM cloud as backend

---

roadmap.md

Update roadmap for 2020
Fixes #468
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/476)

Update roadmap for 2020

---

kubeflow/fairing/kubernetes/manager.py
kubeflow/fairing/utils.py
tests/integration/kubernetes/test_buck_apply.py

Add functions to apply Kubernetes objects
```
from kubeflow.fairing.kubernetes.manager import KubeManager
kubeflow_client = KubeManager()
spec = '''...'''
specs = [ ... ]
kubeflow_client.apply_namespaced_object(spec, 'create|patch|replace|delete')
kubeflow_client.apply_namespaced_objects(specs, 'create|patch|replace|delete')
```
Fixes #453

Add functions to apply Kubernetes objects

---

kubeflow/fairing/kubernetes/utils.py
tests/unit/kubernetes/test_utils.py

Support specifying GPU resource

---

kubeflow/fairing/__init__.py
kubeflow/fairing/builders/base_builder.py
kubeflow/fairing/builders/builder.py
setup.py

Sometimes, user wants to use an existing image to deployer (or build without Fairing), instead of rebuild image. The PR is going to allow user specify existing image.
And release new one in Pypi to include recent fixes. Thanks.

Allow user specify existing image

---

kubeflow/fairing/deployers/tfjob/tfjob.py

1. Do not attach GPU resource for PS pod.
2. Update the Chief default value to 0, since sometimes, just need worker and PS.
Fixes #504

Detach GPU from TFJob PS Spec

---

README.md

Since someone try to install Fairing by `pip install fairing`, instead of `pip install kubeflow-fairing`, we cannot remove the `fairing` in pypi, so update Readme file to show that. Thanks.
Fixes #506

update readme file for how to install kubeflow fairing

---

requirements.txt

Add requirements to avoid tornado AttributeError
Fixes #508 
```release-note
```

add requirements to avoid tornado AttributeError

---

MANIFEST.in
setup.py

Fix problem that cannot find requirements.txt, see more in #496 
```
(python36) [root@jinchi1 ~]# wget https://test-files.pythonhosted.org/packages/fd/d0/f79c8491c7ac5b095377407307593528b652a58b465a3f82f8972ebaa415/kubeflow-fairing-0.7.3.tar.gz
--2020-06-18 02:05:45--  https://test-files.pythonhosted.org/packages/fd/d0/f79c8491c7ac5b095377407307593528b652a58b465a3f82f8972ebaa415/kubeflow-fairing-0.7.3.tar.gz
Resolving test-files.pythonhosted.org (test-files.pythonhosted.org)... 151.101.65.63, 151.101.129.63, 151.101.1.63, ...
Connecting to test-files.pythonhosted.org (test-files.pythonhosted.org)|151.101.65.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 99427 (97K) [application/x-tar]
Saving to: …
```

Fix problem that cannot find requirements.txt

---

kubeflow/fairing/ml_tasks/tasks.py

Support setting output_map on TrainJob, see more in #459 
Fixes #459 
```release-note
```

Support setting output_map on TrainJob

---

kubeflow/fairing/__init__.py
setup.py

Recently we fixed some bugs and merged some enhancement, I think that's ready to release kubeflow-fairing 1.0.0. Thanks.
Fixes #503

Release kubeflow-fairing 1.0.0

---

kubeflow/fairing/kubernetes/utils.py
tests/unit/kubernetes/test_utils.py

Support configuring environment variables
Fixes #492 
```release-note
```

Support configuring environment variables

---

kubeflow/fairing/constants/constants.py
kubeflow/fairing/kubernetes/utils.py

Support mount secret and config map for deployer
Fixes #519 
```release-note
```

Support mount secret and config map for deployer

---

kubeflow/fairing/__init__.py
setup.py

Release kubeflow0-fairing v1.0.1
Fixes #
```release-note
```

Release kubeflow-fairing v1.0.1

---

kubeflow/fairing/frameworks/utils.py

This allows for fairing lightgbm wrapper, to scale well with the
number of machines, and still retains the existing functionality
for cases with smaller num_machines ( 500 ).
Fixes #529 
```release-note
Updated lightgbm wrapper's nslookup to wait based on the size of machines, still retains the previous functionality of waiting for 600 seconds when the num_machines is smaller than 500, for cases where it's larger the maximum wait is (num_machines*1.2) seconds. 
```

update fairing/lightgbm retries to scale with num_machines

---

OWNERS

I have been contributing to fairing for sometime, reviewed and helped on much issue and PRs, please add me as reviewer, thanks. @jinchihe

Add pugangxa as reviewer

---

kubeflow/fairing/__init__.py
setup.py

There are some bug fixes and enhancements, such as https://github.com/kubeflow/fairing/issues/529
Fixes #
```release-note
Fixed bugs and some enhancements such as Fairing nslookup increase retries
```

Release Kubeflow Fairing 1.0.2

---

kubeflow/fairing/builders/cluster/cluster.py

Set container command from preprocessor when using cluster builder
Fixes #538 
```release-note
```

Fix dockerfile processing behavior of cluster builder
