kubeflow/fairing

README.md, setup.py
* Fixes the url in `setup.py`
* Removes mention of serving from the doc for now. We may want to add that back later when/if we implement a more solid solution but for now it's a bit misleading.
cc @r2d4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/17)
=> Update readme & url in setup.py

setup.py
Current licence classifier is invalid and prevents pushing new release (or test release) with error:
> HTTPError: 400 Client Error: Invalid value for classifiers. Error: 'License :: OSI Approved :: Apache License 2.0' is not a valid choice for this field for url: https://test.pypi.org/legacy/ 
Based on https://pypi.org/pypi?%3Aaction=list_classifiers, the only valid Apache classifier is:   
`License :: OSI Approved :: Apache Software License`
See https://github.com/pypa/warehouse/issues/2996
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/19)
=> Fix licence classifier in setup.py

fairing/training/kubeflow/decorators.py, fairing/training/kubeflow/deployment.py, setup.py
when triggering a non distributed job in kubeflow it will create two pods(1 worker, 1 chief). 
This will fix that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/50)
=> avoid launching both chief and worker pods when running a non distributed job

tests/builders/test_dockerfile.py
we should also add the unit tests as a blocking presubmit once fixed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/56)
=> tests: fix tests

fairing/deployers/job/job.py
Job enforces that the pod template spec not have restart_policy set to 'Always' which is the default value. Deployment, however, enforces that restart_policy is not 'Never', so it must be set in the deployer. 
Temporary workaround until we create the entire spec in the deployer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/96)
=> explicitly set restart_policy to never for job

.travis.yml, fairing/cloud/gcp.py, tests/cloud/test_gcp_creds.py
Currently we are just using a user-provided credentials file or checking the `GOOGLE_APPLICATION_CREDENTIALS` environment variable.
This adds additional checks, e.g. gcloud, allowing authentication with end-user credentials as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/103)
=> Check additional locations when retrieving project_id and credentials

fairing/deployers/job/job.py, fairing/deployers/serving/serving.py, fairing/deployers/tfjob/tfjob.py, fairing/kubernetes/manager.py
+ options to add custom labels for job
+ fixing the fairing-deployer label. right now it always set it to job
+ missing functions in runtime_config.py(crashing the job right now)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/113)
=> add custom labels to deployer

examples/gcp/hello-world-gpu-pytorch.py, fairing/deployers/gcp/gcp.py
Allows the user to specify machine type and resources like GPU.
Ref: https://cloud.google.com/ml-engine/docs/tensorflow/machine-types
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/130)
=>  Adding scale tier as a pass through option to GCP deployer

examples/notebook/deploy-to-gcp.ipynb, fairing/deployers/gcp/gcpserving.py, tests/unit/deployers/gcp/test_gcpserving.py
Fixes #73 
New version of #128, after updating the branch to be in sync with current master. 
Original description: As container-based deployments are not supported, we are currently integrating with the model / version creation API on ML Engine. As a result, this currently won't fit within the standard Fairing preprocess -> build -> deploy workflow.
Also added unit tests and an example notebook.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/134)
=> GCP Serving Deployer

fairing/preprocessors/base.py, fairing/preprocessors/full_notebook.py, requirements.txt, tests/integration/common/test_full_notebook.py, tests/integration/common/test_notebook.ipynb, tests/unit/preprocessors/test_full_notebook_preprocessor.py, tests/unit/preprocessors/test_notebook.ipynb
Fixes #33 
Updates the base preprocessor to not require an executable. This is required because the papermill command format is `papermill <input_notebook> <output_notebook>`, and until now the executable has been appended to the end of the command.
Added the `output_file` argument to full_notebook preprocessor, which specifies the output location of the notebook that has been executed. 
Added papermill to the requirements file. Papermill supports copying the output notebook to a hosted storage service, but this would require appending one of the following suffixes to the requirements: [s3], [gcs], [azure], or [all]. This implementation currently assumes that the user has installed the correct version in their container, but we can also update the requirements file if desired.
---
This …
=> Update full_notebook preprocessor to use Papermill

fairing/preprocessors/full_notebook.py, tests/integration/common/requirements.txt, tests/integration/common/test_full_notebook.py, tests/unit/preprocessors/test_full_notebook_preprocessor.py
Fix test failures by updating tests to use Python base image, install Papermill and notebook as explicit dependencies.
Also fixed an issue where absolute notebook paths weren't getting copied to the container by converting to relative paths.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/171)
=> Update full notebook tests and convert absolute to relative paths

fairing/builders/cluster/cluster.py
We select jobs to retrieve logs for based on labels, so give each build a unique label so we don't accidentally grab an older one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/178)
=> Add unique label to cluster builder job

fairing/deployers/gcp/gcp.py, tests/unit/deployers/gcp/test_gcp.py
Fixes #161
Add an option for a user-specified request dictionary with configuration options, when submitting jobs using the GCP deployer. This allows users to provide arbitrary job configurations, in addition to those that are exposed as top-level arguments.
Merge strategy: top-level arguments will override corresponding values set in the request dictionary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/172)
=> Add job config to GCP deployer

Dockerfile.test, cloudbuild.yaml, examples/prediction/xgboost-high-level-apis.ipynb, fairing/backends/backends.py, fairing/deployers/serving/serving.py, fairing/ml_tasks/tasks.py, fairing/ml_tasks/utils.py, tests/integration/gcp/test_running_in_notebooks.py
Summary of changes:
1. Moved the guess builder logic to backend API. This let's us to customize builders based on the environment. For example, here we are mounting GCP service account creds to the cluster builder when user is in GCP. Once we have #145, we can make cloud build the default builder for GCP managed backend. #173 
1. Added delete method to serving deployer and high level api. This is required for adding an end2end test. 
1. Added an e2e test for examples/predict/xgboost-high-level-apis.
1. Had to put in a alternative to PredictionEndpoint.predict() in the xgboost example due to #179 but in our cloud build environment I was getting connection failure error to the prediction endpoint although i can predict against that endpoint from my local machine. It may be due to #126 as …
=> Adding necessary pod spec mutators to cluster builder in the high level api

.gitignore, Dockerfile.test, fairing/cloud/gcp.py, requirements.txt, tests/integration/common/test_high_level_apis.py, tests/integration/common/test_kubeflow_training.py, tests/integration/gcp/test_gcp_high_level_apis.py, tests/integration/gcp/test_gcs_access.py
Summary:
1. A lot of tests were using constant message that might lead to false positives where a cached output makes the test pass. So I made the test messages to be UUIDs to make tests robust. Additionally, added some delays to print test messages to avoid test flakiness in case of very short lived jobs.
2. GCP Storage client was expecting a service account key and this was breaking in environments where application default credentials are used like GCE instances. So I made it to use underlying auth lib to figure out credential instead of requiring json key.
3. Fixes #183 
4. Updated python version used for tests to 3.7. Seldon only supports 3.6+ so it is better to update the version.
5. Changed base image used in tests to plain python images. This increases isolation between tests. …
=> Test improvements and minor fixes for storage client auth

fairing/deployers/serving/serving.py
* Switch default service type back to LoadBalancer because the notebook
test currently depends on that and there's no easy way to override it
in the notebook.
* I didn't actually run the post-submit tests because I'm not sure how.
Related to #206
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/215)
=> Fix a typo in reference to service_type to fix postsubmit tests

.travis.yml, Dockerfile.test, cloudbuild.yaml, fairing/builders/dockerfile.py, fairing/preprocessors/base.py, prow_config.yaml, requirements.txt
Fixes #213 
This reduces test run time from 20-21 mins to 6-7 mins in cloud build including the cloud build start up time. 
Changes summary:
1. Made the preprocessor output file random instead of a constant. This make is possible to run multiple fairing jobs in parallel in an instance. This is useful for users who are launching multiple jobs in different notebooks in the same instance and also for tests.
2. Bumping up the python version in travis to match post commit test python version
3. Printing top 10 slowest test for improving test run times
4. Moved requests lib to the top of requirements.txt to resolve some deps mismatch issue
5. Using machine type with 8 vCPUs for post commit test. Test machine type with 32 vCPUs (only other choice) but didn't improve the test times considerably. …
=> Making tests run parallel

examples/lightgbm/distributed-training.ipynb, examples/prediction/requirements.txt, fairing/frameworks/lightgbm.py, fairing/frameworks/lightgbm_dist_training_init.py, fairing/frameworks/utils.py, fairing/preprocessors/base.py, tests/integration/gcp/test_running_in_notebooks.py, tests/unit/frameworks/test_lightgbm.py
Summary:
1. Added distribution training support for LightGBM #242 
1. Minor change to requirements.txt in XGBoost example to get its test passing
1. Added integration test for distributed training and prediction tasks
Next tasks for distributed support:
1. Ability to partition and copy training data to worker nodes.
1. Documentation
1. Benchmark distributed training performance
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/259)
=> Added distributed training support for LightGBM

examples/lightgbm/Dockerfile
With parallel downloads and crcmod, the download speed increased by 4x. In my tests on n1-highmem-624 instances, I was getting around 300-350 MBps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/264)
=> Updating gsutil config to improve speed

fairing/cloud/storage.py, fairing/frameworks/lightgbm.py, tests/integration/gcp/test_running_in_notebooks.py, tests/unit/frameworks/test_lightgbm.py
Summary:
1. LightGBM uses .weight file automatically if it exists so to keep the behavior same, .weight file copied from GCS if it exists. https://lightgbm.readthedocs.io/en/latest/Parameters.html#weight-data 
1. Refactored storage utils and created an abstraction to support storage systems other than GCS
1. Added unit tests
1. Created and uploaded .weight file for the integration test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/267)
=> LightGBM - Copies weight file if it exists

fairing/kubernetes/manager.py
Some LB-controller implementation (like ELB) returns not ip but hostname.
This patch adds support of hostname as serving endpoint url.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/266)
=> Support hostname as a serving endpoint

fairing/deployers/job/job.py
right now when we use job deployer the container named randomly. This will fix the name. 
pls suggest if my chosen name is not appropriate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/272)
=> add name to container

examples/lightgbm/distributed-training-data-parallel.ipynb, fairing/frameworks/lightgbm.py, fairing/frameworks/lightgbm_dist_training_init.py, fairing/frameworks/utils.py, tests/unit/frameworks/test_lightgbm.py
Adds support for data parallel mode in LightGBM. The user can specify list of training input files that should be distributed across the workers in a distributed training mode.
Fixes #274 
No
```release-note
Added support for data parallel mode in LightGBM
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/276)
=> Added support for data parallel mode in LightGBM

examples/kubeflow/main.py, examples/kubernetes-in-cluster-builder/main.py
The `set_model` function has been removed in PR #114 , but the main.py files are not updated. Seems only need to call fairing.run, no need set_model. The PR is to remove the set_model calling from main.py. Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/278)
=> remove useless set_model

fairing/backends/backends.py, fairing/builders/cluster/cluster.py, tests/integration/common/test_kubeflow_training.py
Adding ability to specify context_source for kubernetes-related backends.
Kaniko supports not only GCS context, but S3 and GitHub.
For future implementation, we need the ability to change that.
Related #282 
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/281)
=> Add ability to specify context_source for k8s backends

examples/distributed-training/main.py, examples/gcp/hello-world-gpu-pytorch.py, examples/kubeflow-gke/main.py, examples/kubeflow/main.py, examples/kubernetes-in-cluster-builder/main.py, examples/kubernetes/main.py
When I warming up the Kubeflow Fairing, and try some examples for on-prem cluster, I found the defined function/class is not built in the image, so while create pod from the image, the training is not run (some of training function run locally). That's not right. Checked details, I found the need to `set_preprocessor` and point the `function_obj` in the `set_preprocessor`. The RP is to update the example to enhance this. Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/285)
=> update examples to add set_preprocessor

fairing/preprocessors/function.py
Adding a warning if user is using the function preprocessor in non-netebook environment, as below:
```
The FunctionPreProcessor is optimized for using in a notebook or IPython environment. For it to work, the python version should be same for both local python and the python in  the docker. Please look at alternatives like BasePreprocessor or FullNotebookPreprocessor.
```
Fixes #289
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/292)
=> Warn users who are using function preprocessor and not in notebook

fairing/backends/backends.py, fairing/ml_tasks/tasks.py
Should allow user input service type, instead of hard code to `LoadBalancer`.  I know that's needed by notebook, but some uses may want to predict in the cluster, especially for on-prem cases. See more in #293 .
The `service_type` has been defined in the [fairing/deployers/serving/serving.py](https://github.com/kubeflow/fairing/blob/master/fairing/deployers/serving/serving.py#L26), but not expose to user defination functions. The PR is to expose the `service_type` so that user can configuration.
Note that the PR only updates some backends functions  `get_serving_deployer` which has been implemented.
Fixes #293
--- …
=> allow user input service type

fairing/kubernetes/manager.py
When a user runs an older tf-job operator. The error message thrown by fairing is a standard HTTP 404 message, see in #296. We should give better instructions for the user to resolve this situation.
Fixes #277 
The quick way is try to catch the ApiException, and then print some useful message for user, such as below:
```
Failed to create TFJob. Checked the cluster to ensure the TFJob version v1beta2 installed.
Traceback (most recent call last):
File "main.py", line 236, in <module>
fairing.config.run()
File "/opt/kubeflow/python3/python36/lib/python3.6/site-packages/fairing/config.py", line 106, in run
deployer.deploy(pod_spec)
File …
```
=> Better error message when tf-job version mismatch

examples/kfserving/main.py, fairing/config.py, fairing/constants/constants.py, fairing/deployers/kfserving/kfserving.py, fairing/kubernetes/manager.py, tests/unit/deployers/kfserving.py
Support KFServing in Fairing.
Fixes #290 
1. The intergration tests for the kfserving are not added, since the automation platform should not have the kfserving installation. But I tested most of cases in the on-prem cluster, and we can add later once the kfserving is installed for test platform.
2. I updated the `log()` function in the `fairing/kubernetes/manager.py` to satify the implements, since there are two container in the pod, we need to point out which container logs will be got.
```release-note
Support KFServing to deploy model service
```
--- …
=> support kfserving in fairing

tests/workflows/app.yaml
Fixes an issue in E2E test where ks was failing to fetch an old swagger spec. Upgrading the apiversion seems to fix the issue.
```
INFO|2019-07-11T18:51:43|/src/kubeflow/testing/py/kubeflow/testing/util.py|71| level=error msg="find objects: Received status code '404' when trying to retrieve OpenAPI schema for cluster version 'v0.3.1' from URL 'https://raw.githubusercontent.com/kubernetes/kubernetes/v0.3.1/api/openapi-spec/swagger.json'"
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 417, in <module> …
```
=> Upgrading ks version for e2e testing

Dockerfile.test, fairing/builders/cluster/cluster.py, fairing/deployers/job/job.py, fairing/deployers/tfjob/tfjob.py
Specifies the container name when tailing logs after a resource is deployed. Currently we don't specify the name of the container and that works if only one container is present in the pod but in environment like ISTIO, where a sidecar container is present, the tailing functionality breaks.
Fixes #316 
```release-note
```
--- …
=> Specifying exact container while log tailing

fairing/deployers/tfjob/tfjob.py, fairing/kubernetes/manager.py, tests/integration/common/test_kubeflow_training.py
Add a option to let user cleanup tfjob after tfjobs finishes.
Fixes #239
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/311)
=> Add a option to let user cleanup tfjob

examples/prediction/xgboost-high-level-apis.ipynb, fairing/backends/backends.py, fairing/builders/cluster/cluster.py, fairing/builders/cluster/gcs_context.py, fairing/frameworks/lightgbm.py, fairing/ml_tasks/tasks.py, tests/integration/common/test_kubeflow_training.py
Summary:
1. Fixes the default namespace in args from "kubeflow" to current namespace in multiple places. 
1. Correctly passes the build context in GKEBackend
1. Made changes to the XGBoost example to make use of new defaults in the API
1. Fixes #253 
Fixes #253 
```release-note
```
--- …
=> Defaulting to current namespace instead of kubeflow namespace and other minor changes

fairing/preprocessors/converted_notebook.py, tests/unit/preprocessors/test_converted_notebook_preprocessor.py
- Avoid converting to different path if we run preprocessors multiple times
- Change path to the absolute path to fix path error like converting notebook to ".py"
Fixes #319 
/assign @jlewi 
/assign @zhenghuiwang
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/320)
=> Avoid converting to different path if running preprocessor multiple times

fairing/preprocessors/converted_notebook.py
Add logging statements to preprocessors to indicate the file names that preprocessors are dealing with.
Fixes #199 
/assign @jlewi 
/assign @zhenghuiwang
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/334)
=> Add logging to preprocessor.

fairing/config.py
When I set the unreasonable preprocessor incautiously, I got some error message (`Exception: Builder name not found: Python`) which confused me, checked details, there are some mini problems in the `fairing/config.py`, in fact, that's `preprocessor`, instead of `builder`, message problem. The PR is to fix the issue.
```
(python36) [root@jinchi1 kubeflow]# python main.py
Traceback (most recent call last):
File "main.py", line 82, in <module>
fairing.config.run()
File "/opt/kubeflow/python3/python36/lib/python3.6/site-packages/fairing/config.py", line 99, in run
preprocessor = self.get_preprocessor()
File "/opt/kubeflow/python3/python36/lib/python3.6/site-packages/fairing/config.py", line 73, in get_preprocessor
self._preprocessor_name, …
```
=> fix mini message problems in conf

fairing/backends/backends.py, fairing/constants/constants.py, fairing/kubernetes/utils.py, fairing/ml_tasks/tasks.py, tests/integration/onprem/test_pvc_mounting.py
Support mount pvc to job deployer, so the trained model can be saved in the PVC derectly.
Fixes #324 
From muy initial thoughts, that can be implemented by `pod_spec_mutators`, but checked the [adding mechanism](https://github.com/kubeflow/fairing/blob/4f9e007365101443e1230ee206980ed6014f7d31/fairing/deployers/job/job.py#L53) for `pod_spec_mutators`, that's hard to pass the args, but the `pvc_name` should be pass to job, so I updated the `Job` class to let user input `pvc_name` and `pvc_mount` (optional, defaults to `/mnt`).
```release-note
support mounting pvc for job deployer
```
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> support mounting pvc for job deployer

cloudbuild.yaml, tests/integration/gcp/test_gcs_access.py
Disabling a test (test_tfjob_submission_without_gcs_access) that is causing a timeout in the presubmit tests. Created #344 to track this issue.
Fixes #342 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/343)
=> Disabling a test that is causing a timeout in the presubmit tests

fairing/builders/cluster/cluster.py
Fixes that fairing-builder causes an error on kubeflow installed on Amazon EKS when:
* it runs on istio-injection enabled namespace
* it uses EC2 instance profile to access ECR and S3
and turn off istio injection for fairing-builder pod.
Fixes #347
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/348)
=> Disable istio injection for builder

fairing/backends/backends.py, fairing/builders/cluster/azurestorage_context.py
After this change, it is possible to use the Azure backend and storage
context in custom namespaces. Previously, the code was defaulting to
namespace `kubeflow` which might not be the right one in multi-user
multi-namespace setup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/362)
=> Azure backend to work in custom namespaces

kubeflow/fairing/constants/constants.py, kubeflow/fairing/deployers/job/job.py, kubeflow/fairing/kubernetes/manager.py
We are running on v0.4.1 kubeflow and which is on the old version of tfjob operator. since you hardcoded the version we can not use deployer to create tfjob. This PR will provide a way to pass the version through env variable. It also adds  annotations parameter which we need to assign to the pods.
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/351)
=> option to select tfjob version + adding annotation parameter

examples/prediction/xgboost-high-level-apis.ipynb, kubeflow/fairing/backends/backends.py, kubeflow/fairing/deployers/serving/serving.py, kubeflow/fairing/ml_tasks/tasks.py
Fixes #373 #206 
Not sure if this will break post-submit test. Please correct me if I miss something I don't know. 
With this fix, clusterIP svc url can be used for prediction. If `//github.com/kubeflow/fairing/blob/master/examples/prediction/xgboost-high-level-apis.ipynb` is tested in the same kubernetes cluster, it should work. 
```release-note
Use service type ClusterIP by default
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/376)
=> Use service type ClusterIP by default

kubeflow/fairing/ml_tasks/tasks.py
Bug fix
Fixes #
If I run TrainJob with KubernetesBackend and pod_spec_mutators with aws credentials.
TrainJob doesn't pass pod_spec_mutators to backend. So I can't use Amazon S3 in builder.
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/397)
=> Pass pod_spec_mutators to builder BaseTask class

tests/integration/gcp/test_running_in_notebooks.py
Disable xgboost_high_level_api.ipynb notebook run in the test
Fixes #409 
The underlying issue seems to be that the call to make prediction gets invoked before the endpoint is fully ready..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/410)
=> disable xgboost_high_level_api notebook run temproarily

requirements.txt, setup.py
Because `kfserving` SDK version is changed to be consistent with kfserving release (0.2.1),  to avoid confusing user, made decision by kfserving comminication, drop old version, and release new one to align with kfserving current release. so kfserving new release is 0.2.1.0, update fairing accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/415)
=> update kfserving version

.travis.yml
Using `python setup.py install` will install PyPI pre-releases of
packages while `pip install -r requirements.txt` won't do that. This
lead to CI tests failing as reported in #421. This commit updates the CI
build setup to run two parallell tests, one where we don't use
pre-releases and one where we do but allow them to fail and won't wait
on the run to complete either.
Fixes #421
- Closes #422 by providing an alternative approach. The difference was described here: https://github.com/kubeflow/fairing/pull/422#issuecomment-557010381
- I've come across this issue in another project as well where this approach was adopted for a ReadTheDocs build, for a trace to that see https://github.com/jupyterhub/kubespawner/issues/370#issuecomment-555622221. …
=> Test PyPI pre-releases but allow for failures

kubeflow/fairing/config.py
I got following out when execute the example under `fairing/examples/kfserving`:
```huleis-mbp:kfserving llhu$ python3 main.py 
Using preprocessor: <kubeflow.fairing.preprocessors.base.BasePreProcessor object at 0x10ef7c0f0>
Using builder:<kubeflow.fairing.builders.append.append.AppendBuilder object at 0x10ef7c208>
Using deployer:  <kubeflow.fairing.builders.append.append.AppendBuilder object at 0x10ef7c208>
```
The above `builder` and `deployer`'s log are same, In fact, it is logical output bug here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/429)
=> Correct the function's output alert message.

kubeflow/fairing/deployers/tfjob/tfjob.py, kubeflow/fairing/kubernetes/manager.py, requirements.txt
`Kubeflow-tfjob` SDK has been published, we should use the SDK to generate and deploy TFJob, see more in #434 
Fixes #434 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/435)
=> Using Kubeflow-tfjob SDK to deploy TFJob

cloudbuild.yaml, tests/integration/gcp/test_running_in_notebooks.py
There were a lot of random failures observed in fairing CI presubmits. This PR resolves these issues by cleaning up the setup and redeploying to a new fairing ci cluster. 
1. Reduced concurrency to 4 from 8 to ensure the vm is not overwhelmed with open files.
1. switched to a new ci cluster *fairing-ci*
1. Disabled a couple of flaky tests temporarily. Once I resolved the flakiness in them, will reenable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/443)
=> Reset CI tests to ensure stability

kubeflow/fairing/preprocessors/base.py
When the input file does not contain the executable file, the executable file is added to the input file.
If this PR is merged, the job can be executed by specifying only the executable file.
The following code fails because the `executable` is not packed into the container.
https://github.com/kubeflow/fairing/blob/f8dd1518f2ac48a1e888eb7b12aae82b6f0959c6/examples/gcp/hello-world-gpu-pytorch.py#L25-L30
Only `input_files` are packed into the container.
https://github.com/kubeflow/fairing/blob/f8dd1518f2ac48a1e888eb7b12aae82b6f0959c6/kubeflow/fairing/preprocessors/base.py#L20-L25
I understand that there is a demand to run an executable that is already included in the base container.
However, in such cases, the preprocessor adds a prefix to …
=> executable passed to preprocessing should be treated as input file

kubeflow/fairing/builders/cluster/minio_context.py, kubeflow/fairing/cloud/k8s.py
Adds a minio context source for the in-cluster builder.
Fixes #456 
```release-note
Adds a minio context source for in-cluster builder in vanilla k8s clusters.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/458)
=> minio context source for vanilla k8s

kubeflow/fairing/deployers/job/job.py, kubeflow/fairing/deployers/kfserving/kfserving.py, kubeflow/fairing/deployers/pytorchjob/pytorchjob.py, kubeflow/fairing/deployers/tfjob/tfjob.py
Sometimes, User needss to specify the deployers (Job, TFJob, PytorchJob and KFServing) name, the PR is going to support that.
The `generateName` is applied only if `Name` is not specified, so we can configure the `name` option, if the `name=None`, then the `generate_name` option will be applied.
Fixes  #463 #462 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/466)
=> Fairing supports user specify the deployers name

kubeflow/fairing/builders/cluster/minio_context.py, kubeflow/fairing/builders/cluster/s3_context.py
Fix duplicated code in cluster builder. In s3_context.py and minio_context.py, defined args but does not use that, and the `push` option does not work. The PR is going to fix that, remove duplicated code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/471)
=> Fix duplicated code in cluster builder

kubeflow/fairing/deployers/job/job.py, kubeflow/fairing/deployers/kfserving/kfserving.py, kubeflow/fairing/deployers/pytorchjob/pytorchjob.py, kubeflow/fairing/deployers/tfjob/tfjob.py, kubeflow/fairing/kubernetes/manager.py
If user is working in k8s cluster, but want to deploy in another remote cluster using Fairing, Fairing should supports load kube_config from user specified location, as Kubenertes Python API done below.
https://github.com/kubernetes-client/python-base/blob/d30f1e6fd4e2725aae04fa2f4982a4cfec7c682b/config/kube_config.py#L719
Fixes #465 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Support user specified kubeconfig for remote k8s cluster in deployer

kubeflow/fairing/config.py, kubeflow/fairing/constants/constants.py, kubeflow/fairing/frameworks/lightgbm_dist_training_init.py
Our current debug info is so simple,especially, the confuse time stamp, also don't show the target debug file's location ,
[I 200108 13:36:53 config:131] Using preprocessor: <kubeflow.fairing.preprocessors.base.BasePreProcessor object at 0x1017af9b0>
after changed, it will be more meaningful, for example :
INFO|2020-01-08 13:18:33|/Users/llhu/Library/Python/3.7/lib/python/site-packages/werkzeug/_internal.py|122| * Running on http://127.0.0.1:8080/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/447)
=> Enhance the logging info output in the debug model

kubeflow/fairing/cloud/azure.py
Currently Fairing creates new Storage Accounts on Azure (if necessary) that do not use best practices of enabling strict transport security. Azure Security Center will flag these storage accounts.
This PR uses the recommended default (which unfortunately isn't the default in the Python SDK).
References:
https://github.com/Azure-Samples/storage-python-manage#create-account
https://docs.microsoft.com/en-us/azure/storage/common/storage-require-secure-transfer
https://docs.microsoft.com/en-us/python/api/azure-mgmt-storage/azure.mgmt.storage.v2018_07_01.models.storageaccountcreateparameters?view=azure-python
-->
```release-note
NONE
```
--- …
=> Only use secure transport mode for new Azure Storage Accounts

examples/kubeflow/main_ocp.py, kubeflow/fairing/builders/podman/podman.py, kubeflow/fairing/config.py, tests/unit/builders/test_podman.py
Environments like OCP 4 use CRI-O as default container runtime. In order to submit jobs to such environment, need to support podman builder to build image and push image to CRI-O based registry with/without TLS checking.
Fixes #472 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/fairing/474)
=> Add podman builder to support CRI-O runtime

requirements.txt
The `azure` library is deprecated. This uses the correct libraries. This also has the side effect that a lot fewer azure dependencies are being installed. No code changes are necessary.
No changes in functionality or behavior.
=> Updates Azure Requirements

examples/kubernetes-in-cluster-builder/main.py, examples/kubernetes-in-cluster-builder/requirements.txt
Since context_source is not optional now for cluster builder, the previous cluster builder example is updated to use minio context. This example also provides a way to save the model back to minio or s3 for further usage.
Fixes #475
```release-note
```
=> Modify cluster builder example with minio context

kubeflow/fairing/__init__.py, setup.py
There is a problem about azure, that has been fixed in #482 . For now user cannot install `kubeflow-fairing`, we need to refresh the new package in pypi. Thanks.
=> Release kubeflow-fairing 0.7.2

kubeflow/fairing/builders/cluster/minio_context.py, kubeflow/fairing/constants/constants.py
There are fixes for these nasty apt-based bugs included into the current release. For instance, `BentoML` generated Dockerfiles cant build on current default `0.14.0`.
https://github.com/GoogleContainerTools/kaniko/issues/940
https://github.com/GoogleContainerTools/kaniko/issues/793
Updates Kaniko Executor default image to v0.22.0.
```release-note
Updates Kaniko Executor default image to v0.22.0.
```
=> bump KANIKO_IMAGE to include important fixes

kubeflow/fairing/builders/cluster/minio_context.py
I have noticed that, when building with the cluster resource with large image layers, the multiple snapshots that are taken can add a **lot** amount of time to the build. You will  see these as the *Taking snapshot of full filesystem...* logs in the builder logs.
Using a single snapshot at the end of the process should shave quite a bit of time off the build/
```release-note
Reduce cluster build time with Kaniko by making use of "--single-snapshot" ability of executor.
```
=> Use single snapshot to reduce build times

kubeflow/fairing/constants/constants.py, kubeflow/fairing/deployers/job/job.py
This type-o is confusing, but oddly consistent! This change just updates the constants spelling.
=> fix job deployer type-o

kubeflow/fairing/deployers/kfserving/kfserving.py, requirements.txt
1.  There is one problem below, add grpcio as dependency.
```
b/python3.6/site-packages/google/api_core/gapic_v1/__init__.py in <module>
24 if sys.version_info >= (3, 6):
25     from google.api_core.gapic_v1 import config_async  # noqa: F401
---> 26     from google.api_core.gapic_v1 import method_async  # noqa: F401
27     __all__.append("config_async")
28     __all__.append("method_async")
/opt/conda/envs/Python-3.6/lib/python3.6/site-packages/google/api_core/gapic_v1/method_async.py in <module>
18 """
19 
---> 20 from google.api_core import general_helpers, grpc_helpers_async
21 from google.api_core.gapic_v1 import client_info
22 from google.api_core.gapic_v1.method import (_GapicCallable,  # noqa: F401 …
```
=> Add grpcio dependency and fix one bug

kubeflow/fairing/deployers/kfserving/kfserving.py, requirements.txt
Fix bug for V1alpha2TensorRTSpec ImportError
```
from kfserving import V1alpha2TensorRTSpec
ImportError: cannot import name 'V1alpha2TensorRTSpec'
```
Fixes https://github.com/kubeflow/examples/issues/806
```release-note
```
=> Fix bug for V1alpha2TensorRTSpec ImportError

kubeflow/fairing/ml_tasks/tasks.py
This PR fixes a bug in the constructor of PredictionEndpoint, which calls its base class constructor with wrong arguments.
The primary example referenced from the Kubeflow docs, xgboost-high-level-apis.ipynb, was broken before this fix.
=> Fix broken PredictionEndpoint

kubeflow/fairing/kubernetes/utils.py
When kubeflow users using cluster builder in an air-gapped environment, users may want to add specific configuration for their build environment(kaniko executor pod). If there's internal python repository inside of air-gapped environment, users should add extra pip.conf file under /etc path using volume_mounts resource mutator.
Currently there's no sub_path option for volume_mounts and this results replacing whole folder contents of /etc to one pip.conf file. So, this PR add sub_path option to volume_mounts to support mount a file to existing path.
If user omits sub_path option then it'll behave as-is since default value of sub_path is None. So, this PR doesn't break backward compatibility.
**Which issue(s) this PR fixes** *(optional, in `fixes …
=> add sub_path option to volume_mounts

kubeflow/fairing/builders/cluster/cluster.py, kubeflow/fairing/builders/docker/docker.py, kubeflow/fairing/builders/dockerfile.py, kubeflow/fairing/builders/podman/podman.py, tests/unit/builders/test_dockerfile.py
As I wrote before(https://github.com/kubeflow/fairing/pull/530), if user of base image is non-root then pip install command should have --user option to avoid permission problem. Also, $HOME/.local/lib path should be included to PATH variable for package executable.
However, there's no easy way to get value of home path unless it is explicitly set by ENV directive. 
So, I added executable_path_prefix option to specify home path of non-root user.
If executable_path_prefix is given, ENV directive will be added to include $HOME/.local/lib.
Fairing user doesn't need to specify executable_path_prefix if $HOME/.local/lib path is already included in a base image.
Base image with root user will be processed same as before.
There can be a better way of …
=> Add conditional statement to dockerfile considering user of base image

kubeflow/fairing/preprocessors/function.py
I've encountered the issue similar to described in https://github.com/kubeflow/fairing/issues/452.
It occurs when user uses function preprocessor + cloudpicke version containing cloudpickle_fast.py + python 3.8+.
The root cause is that newer versions of cloudpickle contain cloudpickle_fast.py and that file isn't copied by preprocessor during image preparation.
So, this PR aims to append mentioned above file along with the rest of cloudpickle package.
By the way, what's the reason for copying that package into image ? Wouldn't it be better to copy egg there f.e. and install it on start up ?
=> Fix for failing Training Job on py 3.8+
